name: Gemini - iRacing Bot

# Tylko ręczne uruchamianie przyciskiem
on:
  workflow_dispatch: # Tylko ręczne uruchamianie przyciskiem

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pobranie kodu
      uses: actions/checkout@v3

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalacja bibliotek
      run: pip install requests

    - name: Uruchomienie Bota
      env:
        IR_CLIENT_ID: ${{ secrets.IR_CLIENT_ID }}
        IR_CLIENT_SECRET: ${{ secrets.IR_CLIENT_SECRET }}
        IR_EMAIL: ${{ secrets.IR_EMAIL }}
        IR_PASSWORD: ${{ secrets.IR_PASSWORD }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: python gemini_bot.py
